apiVersion: v1
kind: Namespace
metadata:
  name: fastapi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fastapi
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: fastapi-tutorial:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  namespace: fastapi
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
